name: C/C++ CI

on:
  push:
    branches: [ "level-scripts" ]
  pull_request:
    branches: [ "level-scripts" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, Linux]
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        submodules: recursive
    - name: make
      run: |
            export PATH=/opt/wonderful/bin:$PATH
            export WONDERFUL_TOOLCHAIN=/opt/wonderful
            export BLOCKSDS=/opt/wonderful/thirdparty/blocksds/core
            export BLOCKSDSEXT=/opt/wonderful/thirdparty/blocksds/external
            cd ./libs/squirrel
            cmake --fresh -DCMAKE_TOOLCHAIN_FILE=/opt/blocksds/core/cmake/BlocksDS.cmake -DDISABLE_DYNAMIC=ON -DSQ_DISABLE_INTERPRETER=ON ./CMakeLists.txt 
            make
            cd ../../
            make
            mkdir -p "./upload/_nds/PortalDS/levels/"
            cp ./assets/Maps/*.vmf ./upload/_nds/PortalDS/levels/
            cp ./Portal-DS.nds ./upload/
    - uses:
          actions/upload-artifact@v4
      with:
       name: Portal DS
       path: ./upload

    #- name: clean
    #  run: |
    #        cd C:\actions-runner\
    #        Remove-Item -Recurse -force .\Portal-DS\
